import vazirFont from "@/constants/localFonts"
import "../styles/globals.css"
import Header from "@/components/Header"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans`}>
          <div className=" w-full">
            <Header />
          </div>
          <div className=" container xl:max-w-screen-xl">{children}</div>
      </body>
    </html>
  )
}
